name: "Check external links"

on:
#  push: 
#    branches: [ main ]
#  pull_request:
#    types:
#      - opened
#      - synchronize
#      - reopened
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  test:
    if: ${{ github.repository == 'splunk/public-o11y-docs' || github.repository == 'splunk/private-o11y-docs' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          #folder-path: './docs/markdown_files'
          base-branch: 'main'
          file-extension: '.rst'
          max-depth: 2
          #check-modified-files-only: 'yes'

