name: Repo Sync

on:
  workflow_dispatch:
  schedule: 
    - cron: "*/5 * * * *"
    
permissions:
  contents: write
  pull-requests: write

jobs:
 repo-sync:
    name: Synchronize repositories
    if: ${{ github.repository == 'splunk/public-o11y-docs' || github.repository == 'splunk/private-o11y-docs' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: ${{ secrets.SOURCE_REPO }}
        source_branch: main
        destination_branch: ${{ secrets.INTERMEDIATE_BRANCH }}
        github_token: ${{ secrets.MY_TOKEN }}
    - name: Create pull request
      uses: gr2m/create-or-update-pull-request-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        title: "Pulling ${{ github.ref }} into main"
        body: "This PR synchronizes the public and private docs repo."
        branch: "main"
        labels: sync
        update-pull-request-title-and-body: false        
